[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend = "setuptools.build_meta"


[tool.isort]
profile = "black"
force_sort_within_sections = "False"
order_by_type = "False"

[tool.black]
target_version = ["py37", "py38", "py39"]

[bdist_wheel]
universal = 1
