name: Run Precommit
on:
  push

jobs:
  publish-test:
    name: Pre-Commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: >-
          python -m
          pip install
          pre-commit
          --user

      - uses: actions/cache@v1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit first time
        id: first_pre_commit
        run: >-
          pre-commit
          run
          --all-files
        continue-on-error: true

      - name: Push Changes to git repository
        shell: bash
        if: failure()
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]" && \
          git add -- . ':!.github' && \
          git commit -m 'Pre-Commit' && \
          git push

      - name: Run pre-commit Second time
        if: success()
        run: >-
          pre-commit
          run
          --all-files