name: Publish to PyPI
on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  publish-test:
    name: Publish to PyPI Test
    runs-on: ubuntu-latest
    steps:
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
         
    publish:
      name: Publish to PyPI
      runs-on: ubuntu-latest
      needs: publish-test
      steps:
        - name: Publish package to TestPyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
          
    
